#!/usr/bin/env bash
# Regenerate Python bindings from protos/*.proto (protobuf + gRPC).
# Requires: pip install grpcio-tools
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$ROOT_DIR"

# Use the project venv when present so grpcio-tools matches installed grpcio.
if [[ -z "${PYTHON:-}" ]]; then
  if [[ -x ".venv2/bin/python" ]]; then
    PYTHON=".venv2/bin/python"
  elif [[ -x ".venv/bin/python" ]]; then
    PYTHON=".venv/bin/python"
  else
    PYTHON="python"
  fi
fi

mkdir -p GRPC/stubs
touch GRPC/stubs/__init__.py

find protos -name "*.proto" | xargs "$PYTHON" -m grpc_tools.protoc \
  -Iprotos \
  --python_out=GRPC/stubs \
  --pyi_out=GRPC/stubs \
  --grpc_python_out=GRPC/stubs

# The gRPC plugin emits sibling imports; GRPC/stubs is a package.
"$PYTHON" <<'PY'
import re
from pathlib import Path

marker = "# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!\n"
pyright_block = marker + "# pyright: reportAttributeAccessIssue=false\n"
import_pattern = re.compile(r"^import (\w+_pb2) as (\w+)$", re.MULTILINE)

for path in Path("compiler_generated").glob("*_pb2_grpc.py"):
    text = path.read_text(encoding="utf-8")
    new_text, count = import_pattern.subn(
        r"from . import \1 as \2",
        text,
    )
    if count == 0 and "from . import" not in text:
        raise SystemExit(
            f"{path}: no protobuf sibling import found; grpc generator output changed."
        )
    if marker in new_text and pyright_block not in new_text:
        new_text = new_text.replace(marker, pyright_block, 1)
    path.write_text(new_text, encoding="utf-8")
    print(f"OK: patched {path}")
PY

echo "OK: wrote compiler_generated protobuf and gRPC stubs"
